const createStageProgress = (status = 'in_progress', progress = 30) => [
  {
    stage_number: 1,
    status,
    progress,
    is_current: true,
    notes: '基础信息已录入，等待后续补充阶段详情',
  },
  {
    stage_number: 2,
    status: 'not_started',
    progress: 0,
    is_current: false,
    notes: '',
  },
  {
    stage_number: 3,
    status: 'not_started',
    progress: 0,
    is_current: false,
    notes: '',
  },
]

export const MOCK_PUX_MEMBERS = [
  {
    id: 'seed-rongruo',
    name: '容若',
    product_line: 'Coohom/AINative',
    po_name: '锐仔',
    join_date: '2026-04-01',
    stage_progress: createStageProgress('in_progress', 38),
    milestones: [{ id: 'm1', title: '名单初始化', date: '2026-04-20' }],
  },
  {
    id: 'seed-tuyi',
    name: '图伊',
    product_line: 'Coohom/商业增长',
    po_name: '锐仔',
    join_date: '2026-04-01',
    stage_progress: createStageProgress('in_progress', 32),
    milestones: [],
  },
  {
    id: 'seed-canger',
    name: '沧耳',
    product_line: 'Aholo平台',
    po_name: '邪神',
    join_date: '2026-04-01',
    stage_progress: createStageProgress('in_progress', 28),
    milestones: [],
  },
  {
    id: 'seed-ningmu',
    name: '柠木',
    product_line: 'Coohom/企业产品',
    po_name: '九一',
    join_date: '2026-04-01',
    stage_progress: createStageProgress('in_progress', 30),
    milestones: [],
  },
  {
    id: 'seed-shenle',
    name: '神乐',
    product_line: '酷家乐工具/make',
    po_name: '拾厘',
    join_date: '2026-04-01',
    stage_progress: createStageProgress('in_progress', 35),
    milestones: [],
  },
  {
    id: 'seed-kankan',
    name: '看看',
    product_line: '棚拍',
    po_name: '努努',
    join_date: '2026-04-01',
    stage_progress: createStageProgress('in_progress', 26),
    milestones: [],
  },
  {
    id: 'seed-putao',
    name: '葡萄（备选）',
    product_line: '酷家乐工具/工业仿真',
    po_name: '织墨',
    join_date: '2026-04-01',
    stage_progress: createStageProgress('not_started', 0),
    milestones: [],
  },
  {
    id: 'seed-yaoyi',
    name: '瑶一（备选）',
    product_line: '建筑结构/户型',
    po_name: '米兔',
    join_date: '2026-04-01',
    stage_progress: createStageProgress('not_started', 0),
    milestones: [],
  },
  {
    id: 'seed-yuluo',
    name: '雨落（备选）',
    product_line: 'Coohom/商业增长&平台工具',
    po_name: '霄凡/锐仔',
    join_date: '2026-04-01',
    stage_progress: createStageProgress('not_started', 0),
    milestones: [],
  },
  {
    id: 'seed-liman',
    name: '黎漫（备选）',
    product_line: '酷家乐工具/KAF（后续可能渲染）',
    po_name: '乃量/天哲',
    join_date: '2026-04-01',
    stage_progress: createStageProgress('not_started', 0),
    milestones: [],
  },
]

